DROP SEQUENCE BOOKS_INDEX_SEQ;
DROP SEQUENCE AUTHORS_INDEX_SEQ;
DROP SEQUENCE ORDERS_INDEX_SEQ;
DROP SEQUENCE REVIEWS_INDEX_SEQ;

CREATE SEQUENCE BOOKS_INDEX_SEQ
  INCREMENT BY 1
  START WITH 1
  NOCYCLE
  ORDER;
  
CREATE SEQUENCE AUTHORS_INDEX_SEQ
  INCREMENT BY 1
  START WITH 1
  NOCYCLE
  ORDER;
  
CREATE SEQUENCE ORDERS_INDEX_SEQ
  INCREMENT BY 1
  START WITH 1
  NOCYCLE
  ORDER;
  
CREATE SEQUENCE REVIEWS_INDEX_SEQ
INCREMENT BY 1
START WITH 1
NOCYCLE
ORDER;

