ALTER SESSION SET "_oracle_script" = TRUE; 
DROP ROLE MANAGER_ROLE;
DROP USER MANAGER_CORE;
DROP USER SUP_MANAGER;
DROP ROLE CLIENT_ROLE;
DROP USER CLIENT_CORE;

CREATE TABLESPACE TS_COURSE
  DATAFILE 'C:\APP\ORA_ADMIN\ORADATA\ORCL\TS_COURSE.DBF'
SIZE 32M 
AUTOEXTEND ON NEXT 5M 
LOGGING
ONLINE;

CREATE ROLE PROGRAM_ROLE;

GRANT
  CREATE TABLE,
  CREATE PROCEDURE,
  CREATE SEQUENCE,
  CREATE CLUSTER,
  CREATE SYNONYM,
  CREATE PUBLIC SYNONYM,
  CREATE VIEW,
  CREATE MATERIALIZED VIEW,
  CREATE ROLE, 
  CREATE USER,
  CREATE JOB
TO PROGRAM_ROLE;

CREATE USER PROGRAM_CORE IDENTIFIED BY 12345
  DEFAULT TABLESPACE TS_COURSE;

GRANT PROGRAM_ROLE TO PROGRAM_CORE;
GRANT CREATE SESSION TO PROGRAM_CORE WITH ADMIN OPTION;
GRANT CREATE USER TO PROGRAM_CORE;
GRANT CREATE ROLE TO PROGRAM_CORE WITH ADMIN OPTION;

DROP ROLE GUEST_ROLE;
DROP ROLE CLIENT_ROLE;
DROP ROLE MANAGER_ROLE;
DROP ROLE PUBLISHER_ROLE;

DROP USER GUEST_CORE;
DROP USER MANAGER_CORE;
DROP USER CLIENT_CORE;
DROP USER SUP_MANAGER;
DROP USER PUBLISHER_CORE;


CREATE ROLE PUBLISHER_ROLE;
CREATE ROLE MANAGER_ROLE;
CREATE ROLE CLIENT_ROLE;
CREATE ROLE PUBLISHER_ROLE;

CREATE USER MANAGER_CORE IDENTIFIED BY 12345 
  DEFAULT TABLESPACE TS_COURSE; 

CREATE USER PUBLISHER_CORE IDENTIFIED BY 12345 
  DEFAULT TABLESPACE TS_COURSE; 

CREATE USER CLIENT_CORE IDENTIFIED BY 12345 
  DEFAULT TABLESPACE TS_COURSE; 
  
CREATE USER SUP_MANAGER IDENTIFIED BY 12345 
  DEFAULT TABLESPACE TS_COURSE; 

GRANT CREATE SESSION TO MANAGER_CORE;
GRANT CREATE SESSION TO PUBLISHER_CORE;
GRANT CREATE SESSION TO SUP_MANAGER;
GRANT CREATE SESSION TO CLIENT_CORE;

GRANT MANAGER_ROLE TO MANAGER_CORE;
GRANT CLIENT_ROLE TO MANAGER_CORE;
GRANT MANAGER_ROLE TO SUP_MANAGER;
GRANT CLIENT_ROLE TO SUP_MANAGER;
GRANT PUBLISHER_ROLE TO PUBLISHER_CORE;
GRANT CLIENT_ROLE TO PUBLISHER_CORE;
GRANT CLIENT_ROLE TO CLIENT_CORE;

CREATE ROLE GUEST_ROLE;


CREATE USER GUEST_CORE IDENTIFIED BY 12345 
DEFAULT TABLESPACE TS_COURSE; 
GRANT CREATE SESSION TO GUEST_CORE;

GRANT GUEST_ROLE TO GUEST_CORE;
GRANT CLIENT_ROLE TO GUEST_CORE;

  
  